# database.yml
# ============
#
# The `config/database.yml` file contains your custom settings for connecting
# the software to a database. You must create the databases you plan to use
# and add their connection details here to use the software.
#
# Format
# ------
#
# This file is split into sections describing different environments, each
# optimized for a different use. If you're only using the software, you
# only need to configure the "production" environment.
#
# Lines starting with an octothorpe ("#") are comments. Uncommented,
# unindented lines start a new environment (e.g., "production"). Indented
# lines below an unindented line are settings related to that environment.
#
# Example
# -------
#
#     # Section describing the "production" environment, don't change this line:
#     production:
#         # Connect to a database named "citizenry":
#         database: citizenry
#         # Connect to this database as the "root" user:
#         username: root
#         # Connect to this database using "mypassword" as the password:
#         password: mypassword
#         # Use "utf8" as the database character encoding, don't change this line:
#         encoding: utf8
#         # Use a MySQL database, don't change this line:
#         adapter: mysql2
#
# Environments
# ------------
#
# The "production" environment is optimized for fast performance, like when
# you deploy the software for use in your organization. It is used when:
# * Starting a console with: rails console production
# * Starting a server with: rails server -e production
# * Running a rake task with: rake RAILS_ENV=production ...
production:
  database: citizenry
  username: root
  password:
  encoding: utf8
  adapter: mysql2

# The "development" environment is optimized for those developing the
# software and reloads code as it's modified. It is used when:
# * Starting a console with: rails console
# * Starting a server with: rails server
# * Running a rake task with: rake ...
development:
  database: citizenry_dev
  username: root
  password:
  encoding: utf8
  adapter: mysql2

# The "test" environment is used for running tests. WARNING: The database
# defined for this will be erased and re-generated from your development
# database when you run "rake". Do NOT set this db to the same as
# "development" or "production".
test:
  database: citizenry_test
  username: root
  password:
  encoding: utf8
  adapter: mysql2
